{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:TxTest", "name": "test_parse_outputs", "time": 0.00028443336486816406, "type": "failure", "errtype": "builtins.AssertionError", "message": "0 != 2", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/DustinStanton/tx-outputs-jsong-pb-sf-072618/test/index_test.py\", line 11, in test_parse_outputs\n    self.assertEqual(len(tx.tx_outs), 2)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 0 != 2\n"}]}